### ISSUE TITLE
make p4ofagent error

### ISSUE THREAD

**Issue by dannyxx001** [p4lang/p4ofagent#22]
Hello,
When I follow the steps to make p4ofagent, it show me the following error:
src/state.h:26:23: fatal error: p4_sim/pd.h: No such file or directory
 #include "p4_sim/pd.h"
Could anyone tell me where I can find the correct header files or how to generate them?
Thank you.

**Comment by pierce-m** [comment]
Hi, did you set CPPFLAGS=-D_BMV2_ ? It looks like the state.h is trying to include a file that only gets generated in the context of p4factory. If you want to make and/or install p4ofagent independently of p4factory, you have to build with _BMV2_ defined.

**Comment by dannyxx001** [comment]
I really appreciated your reply, and I 'm sorry for late response.
Let's get down to business. Can you show me your command to build the p4ofagent? Because I'm try to add the option 'CPPFLAGS=-D_BMV2_' in 'make p4ofagent'. And it shows me the same error. Maybe I should clean something or I just miss something?
Thank you.

**Comment by pierce-m** [comment]
I just rebuilt on my machine using the steps in the README. Maybe try a make clean and rebuild? Do you have the behavioral model installed?

**Comment by dannyxx001** [comment]
I also follow the steps in the README. And I had tried `make clean` and rebuild. It still showed me the same error. So should I install behavioral model first before installing the p4ofagent?

**Comment by pierce-m** [comment]
Hi, yes you need to install the behavioral-model first. I will update the README to reflect that. But the error you are seeing results from not defining the _BMV2_ macro...see this line (https://github.com/p4lang/p4ofagent/blob/master/src/state.h#L33). Exactly how are you trying to build? Can you copy your script into a comment here?

**Comment by dannyxx001** [comment]
I use the behavioral-model and p4ofagent repository from p4factory's submodules. And I had tried to install behavioral-model. Then I follow the steps in README to install p4ofagent.
`./autogen.sh`
`./configure`
`make p4ofagent CPPFLAGS=-D_BMV2_`
Am I correct?
p.s. I had done `git submodule update --init --recursive`.
Thank you for your reply. :)

**Comment by pierce-m** [comment]
Hi, so what you're doing seems correct to me, and I have no idea (without being able to check out your environment) why you are getting this error. The best I can do is link you to [this](https://github.com/p4lang/switch/blob/master/CI/travis/install-p4ofagent.sh) file. This is how we build p4ofagent repository with bmv2 for the regression that is currently passing in p4lang/switch. Good luck.

**Comment by Wasdns** [comment]
Hi, I met the same error when I tried `make p4ofagent`. I followed the README carefully the same as @dannyxx001 . I have no idea about it, could you tell me how you fixed this problem before? Thank you!

**Comment by Wasdns** [comment]
Update：I reinstalled the p4ofagent, but met the same exception. My environment is Ubuntu 14.04, 64bit. And I have installed the p4factory, bmv2 and p4c-bm before.

**Comment by pierce-m** [comment]
Hi,

Are you compiling with CPPFLAGS=-D_BMV2_ ? The include path Danny gave in
his error message ("p4_sim/...") is only relevant when using the p4ofagent
with bmv1, but if you are installing you need to use bmv2.

If the issue persists, please send the error you see.

Thanks,
Pierce

**Comment by Wasdns** [comment]
@pierce-m 

Hi, Pierce. 

Thank you for your reply! Yep, I have compiled with `CPPFLAGS=-D_BMV2_`. The steps I took show below:

```
git submodule update --init --recursive

./autogen.sh

./configure

make p4ofagent CPPFLAGS=-D_BMV2_
```

The exception:

```
In file included from ./inc/loci/loci.h:22:0,
                 from src/state.h:27,
                 from src/callbacks.c:21:
./inc/loci/of_match.h: In function ‘of_memmask’:
./inc/loci/of_match.h:114:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < len; i++) {
                   ^
./inc/loci/of_match.h: In function ‘of_match_more_specific’:
./inc/loci/of_match.h:349:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < sizeof(of_match_fields_t)/sizeof(uint8_t); i++) {
                   ^
./inc/loci/of_match.h: In function ‘of_match_overlap’:
./inc/loci/of_match.h:384:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < sizeof(of_match_fields_t)/sizeof(uint8_t); i++) {
                   ^
In file included from src/callbacks.c:21:0:
src/state.h: At top level:
src/state.h:31:31: fatal error: bm/pdfixed/pd_pre.h: No such file or directory
 #include <bm/pdfixed/pd_pre.h>
                               ^
compilation terminated.
make[2]: *** [src/callbacks.o] Error 1
make[2]: Leaving directory `/home/wasdns/p4ofagent'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/wasdns/p4ofagent'
make: *** [all] Error 2

```
I have run `make clean` after make error. I have no idea about it. :(

Best regards,
Chen.

**Comment by antoninbas** [comment]
When you install bmv2, you need to run `configure` with `--with-pdfixed`. I don't see this mentioned anywhere in this repo's README, so I'll update the instructions.

**Comment by Wasdns** [comment]
@antoninbas Thank you very much. And it fixed my problem.

BTW, I met the same error information:

```
src/state.h:26:23: fatal error: p4_sim/pd.h: No such file or directory
#include "p4_sim/pd.h"
```

I fixed it by remaking the bmv2:

```
cd bmv2
make clean
./configure --with-pdfixed
make
make install
```
