### ISSUE TITLE
Websocket issues in installation (Lighttpd)

### ISSUE THREAD

**Issue by zohaib09** [p4lang/p4ofagent#30]
Hello

I am strugling to install websocket in lighttpd (Linux Debian 9), I am following this link

https://github.com/nori0428/mod_websocket/wiki/for-Ubuntu-Users

Facing following errors

ERROR 1
*Command# ./configure --with-websocket=[ALL, IETF-00, RFC-6455]
*configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: IETF-00,
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: RFC-6455]
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... Invalid configuration `IETF-00,': machine `IETF' not recognized
configure: error: /bin/bash m4/config.sub IETF-00, failed

ERROR 2

Command# make install
Making install in .
make1: se entra en el directorio '/usr/lib/lighttpd/mod_websocket'
(cd ./contrib/gtest-1.7.0; make)
make2: se entra en el directorio '/usr/lib/lighttpd/mod_websocket/contrib/gtest-1.7.0'
/bin/bash ./libtool --tag=CXX --mode=link g++ -pthread -DGTEST_HAS_PTHREAD=1 -g -O2 -o lib/libgtest.la -rpath /usr/local/lib src/gtest-all.lo
libtool: link: g++ -fPIC -DPIC -shared -nostdlib /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/6/crtbeginS.o src/.libs/gtest-all.o -L/usr/lib/gcc/x86_64-linux-gnu/6 -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/6/../../.. -lstdc++ -lm -lc -lgcc_s /usr/lib/gcc/x86_64-linux-gnu/6/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/crtn.o -pthread -g -O2 -pthread -Wl,-soname -Wl,libgtest.so.0 -o lib/.libs/libgtest.so.0.0.0
/usr/bin/ld: src/.libs/gtest-all.o: relocation R_X86_64_PC32 against symbol `_ZN7testing8internal6IsTrueEb' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:923: fallo en las instrucciones para el objetivo 'lib/libgtest.la'
make2: * [lib/libgtest.la] Error 1
make2: se sale del directorio '/usr/lib/lighttpd/mod_websocket/contrib/gtest-1.7.0'
Makefile:806: fallo en las instrucciones para el objetivo 'all-local'
make1: [all-local] Error 2
make1: se sale del directorio '/usr/lib/lighttpd/mod_websocket'
Makefile:390: fallo en las instrucciones para el objetivo 'install-recursive'
make: ** [install-recursive] Error 1

Need some urgent help

**Comment by antoninbas** [comment]
It looks like this was posted here by mistake?
