### ISSUE TITLE
git submodule update failing

### ISSUE THREAD

**Issue by a-s-m-asadujjaman** [p4lang/p4ofagent#33]
git submodule update failing

user@host:~/p4ofagent$ git submodule update --init --recursive
Cloning into '/home/user/p4ofagent/submodules/indigo/submodules/bigcode'...
Warning: Permanently added the ECDSA host key for IP address '140.82.114.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:floodlight/bigcode' into submodule path '/home/asad/p4ofagent/submodules/indigo/submodules/bigcode' failed
Failed to clone 'submodules/bigcode'. Retry scheduled
Cloning into '/home/asad/p4ofagent/submodules/indigo/submodules/infra'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:floodlight/infra' into submodule path '/home/asad/p4ofagent/submodules/indigo/submodules/infra' failed
Failed to clone 'submodules/infra'. Retry scheduled
Cloning into '/home/asad/p4ofagent/submodules/indigo/submodules/loxigen-artifacts'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:floodlight/loxigen-artifacts.git' into submodule path '/home/asad/p4ofagent/submodules/indigo/submodules/loxigen-artifacts' failed
Failed to clone 'submodules/loxigen-artifacts'. Retry scheduled
Cloning into '/home/asad/p4ofagent/submodules/indigo/submodules/bigcode'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:floodlight/bigcode' into submodule path '/home/asad/p4ofagent/submodules/indigo/submodules/bigcode' failed
Failed to clone 'submodules/bigcode' a second time, aborting
Failed to recurse into submodule path 'submodules/indigo'

**Comment by antoninbas** [comment]
Given that these repos are public, I think if you add the SSH key of your local machine to your Github account, you should be able to pull in the submodules.

However, this repository is no longer maintained, and it may not be straightforward to get the code working. I will add a disclaimer in the README. @jnfoster We should probably consider archiving these deprecated repos (p4factory, p4ofagent, ...) to avoid confusion and prevent people form opening new issues.

**Comment by a-s-m-asadujjaman** [comment]
Thanks for the reply. So, which project is recommended for integrating P4 with SDN controllers?

**Comment by antoninbas** [comment]
You can check out the Open Networking Foundation (ONF) ecosystem and in particular the ONOS controller.
There _seems_ to be a shift away from OpenFlow and towards P4-specific APIs (P4Runtime or vendor-specific).

**Comment by a-s-m-asadujjaman** [comment]
I see. Thanks so much.
